version: "2"
services:
    service-a:
        build: ./service-a
        ports:
            - "8080:80"
        links:
            - patrons
    
    patrons:
        build: ./patrons
        expose:
            - 80
