version: "2"
services:
    api:
        build: ./api
        ports:
            - "8080:80"
        links:
            - patrons
            - rabbitmq
    
    patrons:
        build: ./patrons
        expose:
            - "80"
        links:
            - rabbitmq

    table-manager:
        build: ./table-manager
        expose:
            - "80"
        links:
            - rabbitmq
            - patrons

    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
        expose:
            - "5672"