version: "2"
services:
    service-a:
        build: ./service-a
        ports:
            - "8080:80"
        links:
            - patrons
            - rabbitmq
    
    patrons:
        build: ./patrons
        expose:
            - "80"
        links:
            - rabbitmq

    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
        expose:
            - "5672"